# ./gpt-sovits-backend/app/utils/__init__.py
from app.utils.audio_utils import (
    validate_audio_content,
    convert_to_standard_format,
    normalize_audio,
    trim_silence,
    get_audio_info,
)
from app.utils.exceptions import (
    APIException,
    ValidationError,
    AuthenticationError,
    AuthorizationError,
    ResourceNotFoundError,
    ResourceConflictError,
    RateLimitError,
    ServiceUnavailableError,
    FileUploadError,
    AudioProcessingError,
    ModelNotFoundError,
    TaskNotFoundError,
    TaskProcessingError,
)
from app.utils.helpers import (
    generate_unique_filename,
    save_uploaded_file,
    generate_file_hash,
    get_client_ip,
    get_user_agent,
    create_response,
    paginate_query,
    calculate_estimated_time,
    log_user_action,
)
from app.utils.validators import (
    validate_email,
    validate_username,
    validate_password,
    validate_text_length,
    validate_audio_file,
    validate_model_file,
    validate_emotion,
    validate_speed,
    validate_role,
    validate_model_name,
    validate_pagination,
)

__all__ = [
    # audio_utils
    "validate_audio_content",
    "convert_to_standard_format",
    "normalize_audio",
    "trim_silence",
    "get_audio_info",
    # exceptions
    "APIException",
    "ValidationError",
    "AuthenticationError",
    "AuthorizationError",
    "ResourceNotFoundError",
    "ResourceConflictError",
    "RateLimitError",
    "ServiceUnavailableError",
    "FileUploadError",
    "AudioProcessingError",
    "ModelNotFoundError",
    "TaskNotFoundError",
    "TaskProcessingError",
    # helpers
    "generate_unique_filename",
    "save_uploaded_file",
    "generate_file_hash",
    "get_client_ip",
    "get_user_agent",
    "create_response",
    "paginate_query",
    "calculate_estimated_time",
    "log_user_action",
    # validators
    "validate_email",
    "validate_username",
    "validate_password",
    "validate_text_length",
    "validate_audio_file",
    "validate_model_file",
    "validate_emotion",
    "validate_speed",
    "validate_role",
    "validate_model_name",
    "validate_pagination",
]
